service: nodejs-demo-api

provider:
  name: aws
  stage: dev
  region: ap-southeast-1
  runtime: nodejs14.x
  memorySize: 256

functions:
  main:
    handler: src/lambda.handler
    events:
      - http:
          method: ANY
          path: /
          cors: true
      - http:
          method: ANY
          path: '{proxy+}'
          cors: true

plugins:
  - serverless-offline
